"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Navbar from "@/components/Navbar";
import BlogList from "@/components/BlogList";
import { blogData } from "@/public/blog-data";
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={inter.className}>
        <div className="flex flex-col w-screen min-h-screen">
          <Navbar/>
          {children}
        </div>  
        </body>
      </SessionProvider>
    </html>
  );
}
